### ISSUE TITLE
PHP config path and version issue in Ubuntu 18.04

### ISSUE THREAD

**Issue by scaleoutsean** [mrlesmithjr/ansible-apache2#14]
https://github.com/mrlesmithjr/ansible-apache2/blob/ec3aa87e02203c93e1402787a2f0622143c7b1b1/tasks/set_facts.yml#L39

What works on Ubuntu 18.04.3 LTS:

```
- name: Setting PHP Version 7.2
  set_fact:
    # no leading / for template path
    apache2_php_path: etc/php/7.2
    apache2_php_version: 7.2
  when: >
    ansible_distribution == "Ubuntu" and
    ansible_distribution_version >= "16.04"
```
I'm not sure if this also applies to releases >= 18.04, so maybe another or different condition would be appropriate.
Edit: I also created `etc/php/7.2/apache2/` and moved `etc/php/7.0/apache2/php.ini.j2` to that new directory.
