### ISSUE TITLE
Only listens on single port

### ISSUE THREAD

**Issue by cvoltz** [mrlesmithjr/ansible-apache2#15]
If one defines a set of virtual hosts with each running on a different port, the `Listen` command is only created for one of the ports. The port in the `Listen` command is set by `apache2_default_port` but it doesn't support any mechanism for specifying multiple ports. As a result, only one of the virtual hosts will actually be able to accept requests since Apache doesn't automatically listen on the ports specified in the `VirtualHost` directive but only on those specified in the `Listen` directive. For example:
```
- name: Install web-server
  hosts: server
  become: true
  gather_facts: true

  roles:
    - role: mrlesmithjr.apache2
      vars:
        apache2_config: true
        apache2_config_virtual_hosts: true
        apache2_default_port: 443
        apache2_virtual_hosts:
          - documentroot: /var/www/html
            default_site: true
            port: 80
            serveradmin: "{{ apache2_server_admin }}"
            servername: "{{ ansible_fqdn }}"
          - documentroot: /var/www/html
            default_site: true
            port: 443
            serveradmin: "{{ apache2_server_admin }}"
            servername: "{{ ansible_fqdn }}"
```
will only accept requests on port 443 when it is run on CentOS 8.2. Looks like other distros are handled differently and might support at least 80 and 443 but I think they probably would have the same issue if other ports were used (e.g., 8080 and 8443).

Could you please modify the role to allow the `apache2_default_port` to accept a list of ports and generate a `Listen` directive for each port listed?

Also, it wasn't obvious from the documentation that I needed to set `apache2_config` to `true` to get _any_ configuration done. I'm sure you have a reason for defaulting to `false` but it seems like it should be automatically set if any of the other options are selected or the documentation should at least indicate that none of the other options will take affect if it isn't set to `true`.
